### ISSUE TITLE
where is crazyradio-PA  pcb ?

### ISSUE THREAD

**Issue by mathcoder23** [bitcraze/crazyradio-electronics#1]
I am a harware enthusiast,Love your open source projects,and thanks,for we enthusiast provider technology,Have your provider crazyradio-PA pcb?

**Comment by ataffanel** [comment]
We have published the Crazyradio (not-PA) kicad design (see https://github.com/bitcraze/crazyradio-electronics) but not the Crazyradio PA.

**Comment by leon-uhs** [comment]
@ataffanel Is it possible to publish the pcb file of Crazyradio-pa now?

**Comment by knmcguire** [comment]
Hi! We discussed if at our office and we will not release this yet. Perhaps if we have a version 2 of this product at one moment but we are not sure of that yet.
